"""
Type hints for cctbx.array_family.flex module.
"""

from typing import Optional, Tuple, Union, Any
from scitbx.array_family import flex

# Hendrickson Lattman functions
class hendrickson_lattman:
    def __init__(self, a: 'flex.double', b: 'flex.double', 
                 c: Optional['flex.double'] = None, 
                 d: Optional['flex.double'] = None) -> None: ...
    
    def slice(self, i_param: int) -> 'flex.double': ...
    def conj(self) -> 'hendrickson_lattman': ...
    def as_abcd(self) -> Tuple['flex.double', 'flex.double', 'flex.double', 'flex.double']: ...
    def count(self, value: Tuple[float, float, float, float]) -> int: ...
    def all_eq(self, value: Tuple[float, float, float, float]) -> 'flex.bool': ...
    def __add__(self, other: 'hendrickson_lattman') -> 'hendrickson_lattman': ...
    def __mul__(self, scalar: float) -> 'hendrickson_lattman': ...
    def __eq__(self, other: Union['hendrickson_lattman', Tuple[float, float, float, float]]) -> 'flex.bool': ...
    def __ne__(self, other: Union['hendrickson_lattman', Tuple[float, float, float, float]]) -> 'flex.bool': ...

# Miller index functions
class miller_index:
    def __init__(self, h: 'flex.int', k: 'flex.int', l: 'flex.int') -> None: ...
    
    def as_vec3_double(self) -> 'flex.vec3_double': ...
    def fourier_transform_real_part_at_x(self, fourier_coeffs: 'flex.complex_double', 
                                       x: Tuple[float, float, float]) -> float: ...
    def first_index(self, miller_index: Tuple[float, float, float]) -> Optional[int]: ...
    def __neg__(self) -> 'miller_index': ...

# X-ray scatterer functions
class xray_scatterer:
    def __init__(self, scatterers: Tuple[Any, ...]) -> None: ...
    
    def extract_labels(self) -> 'flex.std_string': ...
    def extract_scattering_types(self) -> 'flex.std_string': ...
    def extract_sites(self) -> 'flex.vec3_double': ...
    def set_sites(self, sites: 'flex.vec3_double') -> None: ...
    def extract_occupancies(self) -> 'flex.double': ...
    def set_occupancies(self, occupancies: 'flex.double') -> None: ...
    def extract_fps(self) -> 'flex.double': ...
    def set_fps(self, fps: 'flex.double') -> None: ...
    def extract_fdps(self) -> 'flex.double': ...
    def set_fdps(self, fdps: 'flex.double') -> None: ...
    def extract_u_iso(self) -> 'flex.double': ...
    def set_u_iso(self, u_iso: 'flex.double', selection: 'flex.bool', 
                  unit_cell: Any) -> None: ...
    def extract_u_star(self) -> 'flex.sym_mat3_double': ...
    def set_u_star(self, u_star: 'flex.sym_mat3_double') -> None: ...
    def extract_u_cart(self, unit_cell: Any) -> 'flex.sym_mat3_double': ...
    def set_u_cart(self, unit_cell: Any, u_cart: 'flex.sym_mat3_double') -> None: ...
    def count_anisotropic(self) -> int: ...
    def count_anomalous(self) -> int: ...
    def convert_to_isotropic(self, unit_cell: Any) -> None: ...
    def convert_to_anisotropic(self, unit_cell: Any) -> None: ...
    def scale_adps(self, scale_factor: float) -> None: ...
    def sites_mod_positive(self) -> 'xray_scatterer': ...
    def sites_mod_short(self) -> 'xray_scatterer': ...
    def n_grad_u_iso(self) -> int: ...
    def n_grad_u_aniso(self) -> int: ...
    def extract_grad_u_iso(self) -> 'flex.bool': ... 